"""extended users to include bio and address, and books to include  to trade(bool) and user_review

Revision ID: 09ad562d6b27
Revises: 1d6088378e38
Create Date: 2021-09-17 17:35:56.242445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "09ad562d6b27"
down_revision = "1d6088378e38"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("user_review_stars", sa.Integer(), nullable=True))
    op.add_column(
        "books", sa.Column("user_review_text", sa.String(length=256), nullable=True)
    )
    op.add_column("users", sa.Column("bio", sa.String(length=256), nullable=True))
    op.add_column(
        "users", sa.Column("street_address", sa.String(length=128), nullable=True)
    )
    op.add_column("users", sa.Column("zip_code", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("city", sa.String(length=128), nullable=True))
    op.add_column("users", sa.Column("country", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "country")
    op.drop_column("users", "city")
    op.drop_column("users", "zip_code")
    op.drop_column("users", "street_address")
    op.drop_column("users", "bio")
    op.add_column(
        "books", sa.Column("user_review", sa.VARCHAR(length=256), nullable=True)
    )
    op.drop_column("books", "user_review_text")
    op.drop_column("books", "user_review_stars")
    # ### end Alembic commands ###
