"""empty message

Revision ID: 26fb37d7f200
Revises: 97dc57f320e9
Create Date: 2021-10-15 14:41:38.710151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "26fb37d7f200"
down_revision = "97dc57f320e9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('books', 'user_review')
    # op.add_column("books", "cover")
    # op.add_column(
    #     "books", sa.Column("user_review", sa.VARCHAR(length=256), nullable=True)
    # )

    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column("books", "user_review")
    # op.add_column('books', sa.Column('user_review', sa.VARCHAR(length=256), nullable=True))
    # ### end Alembic commands ###
    pass
