"""adding picture to profile

Revision ID: 54e71a2dfc8a
Revises: 654d1bf638b6
Create Date: 2021-10-15 11:32:45.985533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54e71a2dfc8a'
down_revision = '654d1bf638b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('books', 'user_review')
    op.add_column('users', sa.Column('picture', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'picture')
    #op.add_column('books', sa.Column('user_review', sa.VARCHAR(length=256), nullable=True))
    # ### end Alembic commands ###
