"""even more complete book model2

Revision ID: 91ad65017758
Revises: 3e0455629290
Create Date: 2021-09-13 15:39:34.203732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91ad65017758'
down_revision = '3e0455629290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('read', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'read')
    # ### end Alembic commands ###
