"""cover??

Revision ID: dfccb6f44830
Revises: 26fb37d7f200
Create Date: 2021-10-15 15:13:33.938565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dfccb6f44830"
down_revision = "26fb37d7f200"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('books', sa.Column('cover', sa.String(length=256), nullable=True))
    # op.drop_column('books', 'user_review')
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('books', sa.Column('user_review', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    # op.drop_column('books', 'cover')
    # ### end Alembic commands ###
    pass
